export const SEO = {
  SITE_NAME: "Gram Kumbaram",
  SITE_TITLE_TEMPLATE: "%s | Gram Kumbaram",
  DEFAULT_TITLE: "Gram Kumbaram - Fiziksel Altın Takip ve Portföy Yönetimi",
  DEFAULT_DESCRIPTION:
    "Fiziksel altın yatırımlarınızı takip edin. Canlı gram altın, çeyrek altın, yarım altın ve cumhuriyet altını fiyatları, altın hesaplayıcı ve portföy yönetimi.",
  KEYWORDS: [
    "altın fiyatları",
    "gram altın",
    "çeyrek altın",
    "yarım altın",
    "cumhuriyet altını",
    "altın takip",
    "altın portföy",
    "altın yatırım",
    "altın hesaplayıcı",
    "canlı altın fiyatları",
    "fiziksel altın",
    "altın kumbara",
    "gram kumbaram",
    "altın kar zarar hesaplama",
    "altın alış satış",
    "altın portföy yönetimi",
  ] as string[],
  LOCALE: "tr_TR",
  LANGUAGE: "tr",
  THEME_COLOR: "#FFD700",
  BACKGROUND_COLOR: "#0a0a0a",
} as const;
